name: dev
channels:
  - conda-forge
dependencies:
  - python=3.8
  - boost=1.73.0
  - gcc_linux-64
  - gxx_linux-64  
  - cmake=3.18.0
  - emacs=26.3
  - poco=1.10.1
  - make
  - libclang
  - clangdev
  
